### ISSUE TITLE
Panel button hotkeys

### ISSUE THREAD

**Issue by psarossy** [pymag09/lxc-ui#1]
hey there,

It would be nice to have the [OK] and [Cancel] buttons to have hotkeys on them as it takes a lot of Tab-ing to back out e.g. the Properties menu. I'd say the usual 'o' for OK and 'c'|'esc' for Cancel would be intuitive.

Cheers,
Peter

**Comment by pymag09** [comment]
I am currently working on new version of lxc-ui. And there hotkey for Cancel is already exist. I agree it takes time to get to OK button. So I will assign hotkey in new release. Thank you.

**Comment by pymag09** [comment]
Hi.
Please try new version with hotkeys and more....
Snapshot support also has been added.
