### ISSUE TITLE
Will lxc-ui eventually support unprivileged containers

### ISSUE THREAD

**Issue by bmullan** [pymag09/lxc-ui#2]
lxc-ui today supports privileged containers but how about unprivileged?

**Comment by pymag09** [comment]
Hi.
Sorry, but I don't see any problem with using lxc-ui and unprivileged LXC.
I've just tested it on ubuntu 14.04. 
I've made all preparations to run unprivileged LXC and it works.

**Comment by pymag09** [comment]
I've updated lxc-ui a little. Check the new version.

**Comment by pymag09** [comment]
I've updated lxc-ui a little. Check the new version.

**Comment by bmullan** [comment]
Thanks for the reply.

I guess I don't understand.

The documented command to start lxc-ui.py is:  _sudo ./lxc-ui.py_

So any container it creates will be a "privileged" container not an
"unprivileged" container.

If I try to start lxc-ui.py without sudo it just displays some text then
returns to the CLI prompt.

= = = = = = 
 File "./lxc-ui.py", line 960, in <module>  
 main()  
       File "./lxc-ui.py", line 956, in main                       

keyboard_shortcuts(main_scr)                                                                      

File "./lxc-ui.py", line 825, in keyboard_shortcuts                 

```
  nlxcdata = new_lxc_dialog()                                                                   
```

File "./lxc-ui.py", line 690, in new_lxc_dialog                 

```
   curses.color_pair(3), ' New LXC ', '', False)                                                 
```

File "./lxc-ui.py", line 120, in **init**  
       super(EditBar, self).**init**(x, y, w, h, title_color, regular_text_color, title) 

File "./lxc-ui.py", line 94, in **init**  
       self.win_id = curses.newwin(self.h, self.w, self.y, self.x)  
       _curses.error: curses function returned NULL  

= = = = = =

Note: I use unprivileged containers all the time from a terminal cli prompt so I know unprivileged lxc
         works on my machine

I would expect that to use lxc-ui.py for unprivileged containers you would not need to start it with "sudo".

However, any commands inside lxc-ui that would then need sudo for some reason/function would prompt for the sudo password, use it then return to the non-privileged owner.

thanks

Brian
