### ISSUE TITLE
will lxc-ui support ipv6 configuration of a container

### ISSUE THREAD

**Issue by bmullan** [pymag09/lxc-ui#3]
With ipv6 use growing will lxc-ui implement support for ipv6 configurations

**Comment by pymag09** [comment]
Hi!

No problem. It definitely will support ipv6. :)

**Comment by pymag09** [comment]
Hi.

I have just added ipv6. Please update your lxc-ui.py

**Comment by bmullan** [comment]
I downloaded the latest .zip and start it on ubuntu 14.04
in a terminal by

$ sudo ./lxc-ui.py

The menu appears and looks normal:

[image: Inline image 1]

However, pressing any key in the menu results in some python error:

[image: Inline image 2]

There is some combination of keystrokes affecting the program because
sometimes the 1st keypress
displays the next menu correctly.

I am using Python 2.7.6
Ubuntu 14.04 x64bit

just fyi.

Brian

**Comment by pymag09** [comment]
All my projects written on python3. Description of this project is "python3 linux container manager"
First line in program is "#!/usr/bin/env python3"
And finally, one of the requirement is to install python3-lxc library, described in README.
So, only python3.
Sorry.

**Comment by bmullan** [comment]
I have python3 on my machine.

starting lxc-ui.py using

$  sudo _python3_ ./lxc-ui.py

Doesn't the above command specify to use python3 to execute lxc-ui.py?

Again, the main menu appears fine.
If I press any key though it up with the same screen display after pressing
any main screen command key.

Just to leave no doubt about which python I was using I:

# rm /usr/bin/python

# ln -s /usr/bin/_python3.4_ /usr/bin/python

then execute:
$ sudo ./lxc-ui.py

and I still get corrupted screen that I sent previously whenever I press
any main menu key

brian

**Comment by pymag09** [comment]
Unfortunately I see no images. Just message "[image: Inline image 1]" instead of image. :(
Maybe you just send me text of the error without images?

**Comment by bmullan** [comment]
I just attached the pictures (.png files)

**Comment by pymag09** [comment]
The fact is I don't see any images. :(

**Comment by bmullan** [comment]
I may have found what triggers the errors I am seeing.

If I use a small terminal window (one smaller than the lxc-ui main menu)
and then press any main menu key ... it crashes w/the python tracebacks.

If I use a larger terminal windows (one as big or bigger than the lxc-ui
main menu) then no problem occurs.

I tried to pick out the debug statements out of the mixed display results
for you...

Traceback (most recent call last):
File "./lxc-ui.py", line 969, in <module>
 main()
File "./lxc-ui.py", line 965, in main
 keyboard_shortcuts(main_scr)│
File "./lxc-ui.py", line 834, in keyboard_shortcuts
 nlxcdata = new_lxc_dialog()]
File "./lxc-ui.py", line 699, in new_lxc_dialog
  curses.color_pair(3), ' New LXC ', '', False)
File "./lxc-ui.py", line 120, in **init**
  super(EditBar, self).**init**(x, y, w, h, title_color,
regular_text_color, title)
File "./lxc-ui.py", line 94, in
**init**
  self.win_id = curses.newwin(self.h, self.w, self.y, self.x)
  _curses.error: curses function returned NULL                     │

**Comment by pymag09** [comment]
Hi.
I have fixed problem with window resize or small window.
Also I have added new features like Ctrl+O.
Plus interface has been changed slightly.
Hope you like it.
